server {
    listen 8080;
    listen [::]:8080;
    server_name  _;
    root /usr/share/nginx/html;

    # Proxy to Next.js App
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Static assets (Next.js _next/static)
    location /_next/static/ {
        proxy_pass http://localhost:3000;
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # Public Uploads
    location /uploads/ {
        alias /app/public/uploads/;
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, must-revalidate";
    }

    # Cache fonts
    location ~* \.(woff|woff2|ttf|otf|eot)$ {
        proxy_pass http://localhost:3000;
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
